### ISSUE TITLE
Complete Value proposition hypothesis

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/10X-Users-First#11]
#### User Story
Complete the value proposition hypothesis with this data:

- [ ] Jobs - What are the agencies trying to conduct and get done 
- [x] Pain points
- [x] Gains

**Comment by lalitha-jonnalagadda** [comment]
@annahsebok Worked through the gains section and rearranged the content a tad bit. Moved the hypothesis right below the problem statement, followed by users and their job above the value hypothesis so that the flow works well. Please let me know your thoughts.

**Comment by annahsgraves** [comment]
Sorry I missed this @lalitha-jonnalagadda! Will review in the down time I have with scheduling interviews today.

**Comment by annahsgraves** [comment]
@lalitha-jonnalagadda made some copy edits and tweaks [here](https://github.com/18F/10X-Users-First/wiki/Value-Proposition-Hypothesis). Please take a look when you can and let me know if you have questions.

**Comment by lalitha-jonnalagadda** [comment]
Looks good. Moving this ticket to done.
