### ISSUE TITLE
Read policy documentation

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/10X-Users-First#12]
Finish reading and making necessary notes for the following docs:
- [x] User Testing - Usability.gov - https://digital.gov/2018/04/03/thinking-about-going-agile-5-benefits-your-office-will-reap-with-agile-methods/
- [x] President's Management Agenda Over view - https://www.performance.gov/PMA/PMA.html
- [x] content/uploads/2018/04/ThePresidentsManagementAgenda.pdf
- [x] Improving Customer Experience at Federal Agencies - https://www.performance.gov/CAP/action_plans/FY2018_Q2_Improving_Customer_Experience.pdf

Additional Material added on 7/12/18:
- [ ] https://www.whitehouse.gov/wp-content/uploads/2018/04/M-18-15.pdf
- [ ] https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2015/m-15-14.pdf
- [ ] https://www.whitehouse.gov/wp-content/uploads/2017/11/M-18-12.pdf
- [ ] https://management.cio.gov/ - Especially around FITARA - https://www.congress.gov/113/plaws/publ291/PLAW-113publ291.pdf#page=148%5D
- [ ] https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf
- [x] https://www.whitehouse.gov/wp-content/uploads/2018/06/M-18-19.pdf

#### Acceptance Criteria
Ticket to be closed after reading is complete.

#### Notes
Notes from these policies can be found in the Policy tab of this document - https://docs.google.com/spreadsheets/d/1vP1SRpZdq7VnVVDO6apEjnNaAHIEn1Pu7KOfjAVHJHk/edit#gid=1307479467

**Comment by lalitha-jonnalagadda** [comment]
https://www.performance.gov/CAP/CAP_goal_1.html

Good points around agile and the implementation of Agile best practices to drive IT modernization - driving value by increasing efficiencies of Government IT spending while potentially reducing costs, increasing efficiencies, and enhancing citizen engagement and satisfaction with the services we provide. Might not be directly co-related to the implementation that we are looking for with UCD. Doesn't explicitly state it.

**Comment by lalitha-jonnalagadda** [comment]
Memorandum from OMB - https://www.whitehouse.gov/wp-content/uploads/2018/06/M-18-19.pdf

This memorandum speaks to the overall portfolio and program management for agencies. This memo refers to the stakeholder user group that we are planning on speaking with, who design and allocate funding at the organizations in developing solutions. They clearly outline User driven requirement gathering as way forward. See page 14 for more details. Also ties in perfectly to the mission of UCD - the ultimate goal is to save time, effort and resource sin building products and helping the citizens. They conduct a yearly review with the CFO's, CIO's, program managers, etc per the performance.

**Comment by lalitha-jonnalagadda** [comment]
Additional Material added to the list on 7/12: 
https://www.whitehouse.gov/wp-content/uploads/2018/04/M-18-15.pdf
https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2015/m-15-14.pdf
https://www.whitehouse.gov/wp-content/uploads/2017/11/M-18-12.pdf

**Comment by annahsgraves** [comment]
@lalitha-jonnalagadda would you mind adding any additional items to the acceptance criteria of the issue if we need to read them? It's confusing to me for them to be in a comment because we can't validate that they've been read that way. Thank you :)

**Comment by lalitha-jonnalagadda** [comment]
Added the new docs to the original list @annahsebok Please let me know if that works.

**Comment by annahsgraves** [comment]
Yay thank you @lalitha-jonnalagadda! This way we can check them off when they're read. :)

**Comment by annahsgraves** [comment]
@lalitha-jonnalagadda can you check off the ones you've read so I know where I can start scrubbing in?
