### ISSUE TITLE
Develop research plan

### ISSUE THREAD

**Issue by annahsgraves** [18F/10X-Users-First#13]
#### User Story

As a team member, I need to know our research goals and questions so that we can go into our research interviews prepared. 

#### Background (Optional)

We conducted research in phase 1, but it was solely focused on identifying barriers to conducting user research. In phase 2, we hope to expand on that to better understand agency implementation, pain points, benefits, and resources agencies refer to on user centered design. 

#### Acceptance Criteria

- [x] We have a research plan for stakeholders that includes a script to guide out research interviews
- [x] We have a research plan for users that includes a script to guide out research interviews

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] Clarify vision
- [x] Clarify difference between users and stakeholders (and who makes up each group)
- [x] Define research goals, summarize background, and identify research methods
- [x] Develop recruiting message and screen
- [x] Develop interview guide for stakeholders
- [x] Develop interview guide for users
- [x] Collect feedback
- [x] Refine based on feedback
- [x] Make template for team to take structured notes in

**Comment by annahsgraves** [comment]
[research plan doc](https://docs.google.com/document/d/1SxXfDC_V0Jfogwn1G9MieGC4ZKCnWBgLJ7LMIn478F4/edit#)

**Comment by annahsgraves** [comment]
@lalitha-jonnalagadda let me know what you think about this issue, specifically if we're missing anything.

**Comment by lalitha-jonnalagadda** [comment]
@annahsebok The list looks good for now and I don't notice anything missing. I feel that the template to take notes should be prioritized especially since we are getting ready to start speaking with teams. Let's try and work on it during our working sessions today and tomorrow.

**Comment by annahsgraves** [comment]
Definitely an easy lift @lalitha-jonnalagadda since we've got our script flushed out. I'll have something ready to review during our coworking time today.

**Comment by annahsgraves** [comment]
Template for structured note-taking @lalitha-jonnalagadda: https://docs.google.com/document/d/1y_ShxfBPafwIjFBGNlmwjfoRPqo2TJE_6yLvKS491Jk/edit#heading=h.bgd5zlifoyez

**Comment by annahsgraves** [comment]
@lalitha-jonnalagadda Finished flushing out the [user script portion](https://docs.google.com/document/d/1SxXfDC_V0Jfogwn1G9MieGC4ZKCnWBgLJ7LMIn478F4/edit#heading=h.fbajkll1hy90) of our research plan. Can you take a look and drop any comments or questions you have in the doc?

**Comment by annahsgraves** [comment]
Research plan is done! I'm going to move the post-interview synthesis work into another issue so we can move this to done.
