### ISSUE TITLE
Review Documentation and Resources

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/10X-Users-First#15]
#### User Story

As a team, we would like to capture all the resources/documents that we are reading and analyzing so that we can refer back to these notes when needed.

#### Background (Optional)

As part of the ongoing research for this project, we are reading through several documents and articles that aren't directly related to policy and we would like to capture them here

#### Acceptance Criteria

- [x] Reading has been completed

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] https://www.dta.gov.au
- [x] https://gds.blog.gov.uk
- [x] https://digital.canada.ca/
- [x] https://medium.com/swlh/how-to-remote-user-test-1575b0988353
- [x] BEFORE 7/20: check out https://sftool.gov/ to review the results of our user-centered design. Specific pages to note include; [Explore](https://sftool.gov/explore/green-building/section/76/planted-roof/system-overview), [Helpful Tools](https://sftool.gov/home/about), [Annotated Executive Orders](https://sftool.gov/learn/annotation/447/executive-order-13693-revoked-planning-federal-sustainability-decade), and [User Guides](https://sftool.gov/green-guidance/for/4/project-manager) 
- [x] https://policy.cio.gov/web-policy/analytics
- [x] https://docs.google.com/presentation/d/1KecLuRnqH_ChBRrnmANuqBHMx2z4xd1BgrtuZofKkns/edit#slide=id.g32b18dfd30_0_780
- [x] https://github.com/GSA/recruiter
- [x] https://innovation.gov/toolkit/delivery/#human-centered
- [x] https://www1.nyc.gov/nyc-resources/design-rfp.page

**Comment by annahsgraves** [comment]
@lalitha-jonnalagadda I'm a little bit confused by this — I thought we had discussed splitting up the items as opposed to both of them reviewing so we're not duplicating efforts?

**Comment by lalitha-jonnalagadda** [comment]
@annahsebok  I created this ticket as a master list to hold all documents (non policy, non inventory)  in one place. We can either create dependent tickets on the ones that we want to work on from here or just comment in here on the ones that we will be reading through before we begin so the other one knows. Please let me know if that doesn't work. I haven't written down my tl:dr versions of these and you are welcome to take these. The acceptance criteria is generic and if that is causing confusion, I would be happy to change.

**Comment by annahsgraves** [comment]
Got it! I tweaked the original issue a bit so it's similar to #12 and will start digging in. What *haven't* you read yet, so I know where to start?

**Comment by annahsgraves** [comment]
Perhaps you could check off the ones you're finished with (even if you haven't written your tl;dr versions yet)?

**Comment by lalitha-jonnalagadda** [comment]
Notes: https://www.dta.gov.au and  https://gds.blog.gov.uk both refer to a list of standards for their design and development. GDS has 18 items where as DTA has 13 and both of them start off with talking to users and conducting corresponding research before beginning any development. These standards are a quick checklist to glance through all the steps involved and each step is linked to the corresponding resources that can assist the user with that step. A quick checklist as these will benefit the user in estimating and preparing teams, resources, etc before undertaking UCD. Measuring/validating success of implementing UCD by any organization becomes easy with such checklist as well.

**Comment by annahsgraves** [comment]
For the SF Tool and subsequent materials from Michael Bloom:

- The SF tool exists to support environmentally responsible purchasing for efficient facilities/buildings. It includes sections focused on learning, planning for a project, exploring a virtual building to consider materials and design strategies, procuring environmentally sustainable products, assessing knowledge in federal facility skills, and sharing stories.
- The SF tool was built to help lower waste, utility costs, and ensure sustainability of federal government buildings
- The SF Tool website includes a section focused on an executive order that mandatee the need for sustainable federal buildings
- A project manager of a building project can use the SF Tool to guide them through how to incorporate sustainability into all of their projects.

**Comment by annahsgraves** [comment]
This work was completed
