### ISSUE TITLE
Create a Mural board to capture Research synthesis

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/10X-Users-First#18]
#### User Story
As a team, we would to capture resonating themes, pain points benefits and  from our user research onto a mural board so that we can further synthesize our on going analysis. 

#### Acceptance Criteria

- [x] Create Mural board
- [x] Incorporate analysis from all user interviews onto the board
- [x] Make research board sharable as needed

#### Implementation outline (if higher than "low" effort):

- [x] Categorize information from the interviews into broader buckets - gains, pains, opportunities, etc
- [x] Identify themes that resonate during interviews
- [x] Organize data in the board in order to come up with solution, value proposition
- [x] Define/add metrics to measure benefits

**Comment by lalitha-jonnalagadda** [comment]
@annahsebok This is the board I created for us to discuss today. Will need changes, but we can use this as a starting point - https://app.mural.co/t/gsa6/m/gsa6/1531749339557/53ce108e447241dfae38c16b06c4d8aa6d5ea14f
Let me know if you have trouble accessing it.

**Comment by lalitha-jonnalagadda** [comment]
@anna Added Matt's details to the board as well. Will keep adding to this board as we progress but let me know your feedback so I can edit as needed.

**Comment by annahsgraves** [comment]
This looks awesome @lalitha-jonnalagadda! A few things I'm wondering about:

- We have 14 people we're talking to and I'm not sure there's enough space here for that + synthesis of them all. Is there anything we can shrink/cut/modify to make sure we've got room for all?
- While I so very much appreciate the legend, I'm having a really hard time having to move back and forth between the legend and each person's outputs, and I think this will amplify with even more data. Can we use titles for each column instead?

**Comment by lalitha-jonnalagadda** [comment]
@annahsebok Agree on bullet 2. Will make the changes with titles tomorrow. I do plan on cutting some of the information for each interview over the coming days as well, just didnt want to start off with limited information and go back to re reading the whole interview each time. Will keep you posted as I do.

**Comment by annahsgraves** [comment]
Makes sense @lalitha-jonnalagadda. Let's also chat this morning about how we can work on this together. Ideally, we're doing this synthesis collaboratively.

**Comment by annahsgraves** [comment]
This work was completed.
