### ISSUE TITLE
On going updates to the Mural board 

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/10X-Users-First#19]
#### User Story

As a team, we would like to have the research from our user interviews categorized on the Mural board so that we can analyze the information further. 

#### Acceptance Criteria

- [ ] Create tiles for all the interviewees in Mural
- [ ] Update this ticket when the board is updated with each interview
- [ ] Anna and Lalitha review

#### Implementation outline (if higher than "low" effort):

- [ ] Categorize interview answers into pains, gains, opportunities, metrics, etc
- [ ] Update the Mural Board with the information
- [ ] Draw conclusions and common themes across these interviews

**Comment by annahsgraves** [comment]
This feels like the task breakdown of https://github.com/18F/10X-Users-First/issues/16. Can we merge them instead of having two synthesis related issues? I feel like the real goal here is to complete synthesis, not update mural.

**Comment by lalitha-jonnalagadda** [comment]
Never mind this ticket. Oversight on my end. Closing this ticket.
