### ISSUE TITLE
Create Shipping News template

### ISSUE THREAD

**Issue by lalitha-jonnalagadda** [18F/10X-Users-First#9]
#### User Story
Create an overview document outlining the current progress for User First project similar to the Shipping News document
#### Acceptance Criteria

- [ ] Create Outline document
- [ ] Review with Anna
- [ ] Publish in the "Shipping News Channel"

**Comment by annahsgraves** [comment]
Here's a nice format that I stole for TSP that I've seen used on a few other projects: https://docs.google.com/document/d/1C9mj2rOyoU0qBUAepAi89_hIB4e215zcuF-RlDNfphk/edit

**Comment by lalitha-jonnalagadda** [comment]
Thanks Anna. Here is the one I created for us - https://docs.google.com/document/d/17B4Ci-R601M_yXc9niOz2BRMGZ-Tejwaztj3X3zVwp0/edit# 
We can discuss this during our session this afternoon and finalize the format so I can close this ticket.
